<?php
/**
 * Created by PhpStorm.
 * User: eslider
 * Date: 31.03.18
 * Time: 21:07
 */

namespace app\components;


use app\models\Markets;
use app\models\News;
use app\models\Settings;
use app\models\Stock;

class NewsGeneratorService
{
    public function runSimulation(){
        print("FAKE NEWS GENERATOR\r\n");

        $markets = Markets::find()->all();
        $lastTickSettings = Settings::findOne(['key' => 'lastTick']);


        foreach ($markets as $market){
            $possibleSector = [
                Stock::SECTOR_SERVICE,
                Stock::SECTOR_INDUSTRIAL,
                Stock::SECTOR_AGRICULTURAL
            ];

            foreach ($possibleSector as $sector){
                $possiblePriorities = [
                    News::PRIORITY_HIGH,
                    News::PRIORITY_MEDIUM,
                    News::PRIORITY_LOW
                ];

                $possibleTypes = [
                    News::TYPE_POSITIVE,
                    News::TYPE_NEGATIVE
                ];



                $news = new News();

                $news->fk_market = $market->id;
                $news->priority = $possiblePriorities[rand(0,2)];
                $news->type = $possibleTypes[rand(0,1)];
                $news->sector = $sector;
                $news->tick = $lastTickSettings->value;

                $news->text = "Autogenerated news";
                $news->title = "Auogenerated news";

                $news->save(false);
            }
        }

    }

}